sudo: false

language: python

python:
  - "3.6.3"

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  - pip install pipenv
  - pipenv update

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python manage.py test