# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 15:21
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name=django.contrib.auth.models.User)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='users_logos/')),
            ],
        ),
    ]
